export { default as EditPlayersDialog } from './EditPlayersDialog.vue'
export { default as KanastaScoreDialog } from './KanastaScoreDialog.vue'
export { default as GoHomeButton } from './GoHomeButton.vue'
export { default as NewGameButton } from './NewGameButton.vue'
export { default as StarRealmsCounter } from './StarRealmsCounter.vue'
